apiVersion: apps/v1
kind: Deployment
metadata:
  name: javalogin-deployment
  labels:
    app: javalogin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javalogin
  template:
    metadata:
      labels:
        app: javalogin
    spec:
      containers:
      - name: javalogin-container
        image: vamshidhar1128/javalogin
        ports:
        - containerPort: 8081
